version: "3"
services:
    node89:
        image: "node:8.9"
        user: "node"
        working_dir: /home/node/app/
        ports:
            - "3089:3089"
        environment:
            - DBWEBB_PORT=3089
        volumes:
            - ./:/home/node/app
        command: "npm start"
    node61:
        image: "node:6.11"
        user: "node"
        working_dir: /home/node/app/
        ports:
            - "3061:3061"
        environment:
            - DBWEBB_PORT=3061
        volumes:
            - ./:/home/node/app
        command: "npm start"
    node48:
        image: "node:4.8"
        user: "node"
        working_dir: /home/node/app/
        ports:
            - "3048:3048"
        environment:
            - DBWEBB_PORT=3048
        volumes:
            - ./:/home/node/app
        command: "npm start"
    node_latest:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-latest
        volumes:
            - ./:/app/
        ports:
            - "3000:3000"
    node_7:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-7
        volumes:
            - ./:/app/
        ports:
            - "3000:3000"
    node_6:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-6
        volumes:
            - ./:/app/
        ports:
            - "3000:3000"
