version: "3"
services:
    php71:
        image: php:7.1-apache
        ports:
            - "8071:80"
        volumes:
            - /c/Users/andré/desktop/web/dbwebb-kurser/ramverk2/me/kmom02/docker:/var/www/html
    php70:
        image: php:7.0-apache
        ports:
            - "8070:80"
        volumes:
            - /c/Users/andré/desktop/web/dbwebb-kurser/ramverk2/me/kmom02/docker:/var/www/html
    php56:
        image: php:5.6-apache
        ports:
            - "8056:80"
        volumes:
            - /c/Users/andré/desktop/web/dbwebb-kurser/ramverk2/me/kmom02/docker:/var/www/html
